### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by a727891** [Invisi/gw2-fotm-instabilities#1]
I wanted to drop a thank you for keeping this list updated.

If you would like, you can also mention BlishHud as another consumer/ enduser source using this data in the repo readme.

https://blishhud.com/modules/?module=Soeed.RaidClears
![image](https://github.com/Invisi/gw2-fotm-instabilities/assets/2788304/11bdf37b-767b-46e7-a692-c19e25f9db71)

Thanks again!

**Comment by Invisi** [comment]
Sure, that's a great idea. Thanks for the attribution in your module :)
